# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres:latest
    # restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: caddie_app
    ports:
      - '5432:5432'

  backend:
    image: node:16
    volumes:
      - '.:/app'
    ports:
      - '3001:3001' # Nest
    depends_on:
      - postgres
    working_dir: /app
    command: ["yarn", "workspace", "@caddie/backend", "start:dev"]
    environment:
      # with docker we listen to the postgres network, but it is reachable at @localhost on our post
      DATABASE_URL: postgresql://postgres:password@postgres:5432/caddie_app?schema=public

  frontend:
    image: node:16
    volumes:
      - '.:/app'
    ports:
      - '3000:3000' # React
    depends_on:
      - backend
    working_dir: /app
    command: ["yarn", "workspace", "@caddie/frontend", "start"]