# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: caddie_app
    ports:
      - '5432:5432'

  # nestjs:
  #   container_name: nestjs
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - BUILD_CONTEXT=backend
  #   ports:
  #     - '3001:3000'

  # react:
  #   container_name: react
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - BUILD_CONTEXT=frontend
  #   ports:
  #     - '3000:3000'